# services:
#   nginx:
#     image: nginx:latest
#     volumes:
#       - \\wsl$\docker-desktop-data\data\docker\volumes\nginx\nginx.conf
#     ports: 
#       - "3000:8080"
#       - "3001:8081"
#     restart: always

#   web1:
#     build: .
#     ports:
#       - "8080:8080"

#   web2:
#     build: .
#     ports:
#       - "8081:8081"
    